SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, sum(s.SALES*b.PRICE) AS TOTAL_SALES 
FROM BOOK b
LEFT JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
LEFT JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE s.SALES_DATE LIKE '2022-01%'
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;