SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, COUNT(DISTINCT(O.USER_ID)) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT(O.USER_ID)) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%'),1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
LEFT JOIN USER_INFO U ON O.USER_ID = U.USER_ID
WHERE U.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;