SELECT M.MEMBER_NAME, R.REVIEW_TEXT, LEFT(R.REVIEW_DATE,10) AS REVIEW_DATE
FROM REST_REVIEW R
LEFT JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID = (SELECT MEMBER_ID FROM (SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_COUNT FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY REVIEW_COUNT DESC LIMIT 1)AS Subquery)
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC;