SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT f1
WHERE PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT f2 WHERE f1.CATEGORY = f2.CATEGORY AND (CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'))
ORDER BY PRICE DESC;